workflows:
  build-android:
    name: Build Android APK
    max_build_duration: 10
    environment:
      java: 17
    scripts:
      - ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
